In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [2]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
df = pd.read_csv("C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn0.csv")
df.head()

Var1_1    Var1_2    Var1_3    Var1_4    Var1_5    Var1_6    Var1_7  \
0  0.286275  0.282353  0.282353  0.282353  0.278431  0.282353  0.282353   
1  0.282353  0.282353  0.286275  0.282353  0.286275  0.282353  0.290196   
2  0.290196  0.290196  0.290196  0.290196  0.290196  0.290196  0.290196   
3  0.290196  0.294118  0.294118  0.294118  0.290196  0.298039  0.298039   
4  0.298039  0.298039  0.298039  0.298039  0.301961  0.309804  0.305882   

     Var1_8    Var1_9   Var1_10  ...  Var1_117  Var1_118  Var1_119  Var1_120  \
0  0.282353  0.286275  0.282353  ... -0.666111 -0.596744  0.023087  0.643077   
1  0.282353  0.282353  0.282353  ...  0.066383 -0.114308  0.468330 -0.288977   
2  0.290196  0.290196  0.286275  ... -0.046819 -0.004622 -0.066927  0.497249   
3  0.286275  0.290196  0.294118  ...  0.057576  0.013179  0.070191 -0.076089   
4  0.301961  0.301961  0.298039  ... -0.035611  0.017189  0.073543 -0.049479   

   Var1_121  Var2  Var3    Var4_1    Var4_2    Var4_3  
0  0.884356     4     4  0.239216  0.270588  0.466667  
1 -1.387412    10     4  0.239216  0.266667  0.470588  
2 -0.121266    16     3  0.239216  0.278431  0.478431  
3  0.364632    22     4  0.243137  0.282353  0.482353  
4  0.390944    28     4  0.247059  0.290196  0.501961  

[5 rows x 126 columns]

In [3]:
import tensorflow as tf

In [11]:


# define the input layer with 121 neurons
input_layer = tf.keras.layers.Input(shape=(121,))

# define the first hidden layer with 60 neurons and ReLU activation function
hidden_layer_1 = tf.keras.layers.Dense(60, activation='relu')(input_layer)

# define the second hidden layer with 60 neurons and ReLU activation function
hidden_layer_2 = tf.keras.layers.Dense(60, activation='relu')(hidden_layer_1)

# define the output layer with 3 neurons and sigmoid activation function
output_layer = tf.keras.layers.Dense(3, activation='sigmoid')(hidden_layer_2)

# create the model with input and output layers
model = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

# compile the model with MSE (mean squared error) loss function and Adam optimizer
model.compile(loss='mse', optimizer='adam')

## Training

In [12]:
for i in range(5):
  df = pd.read_csv(f"C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn{i}.csv")
  lst = [i for i in range(0,121)]
  X = df.iloc[:, lst].values
  y = df.iloc[:, [123,124,125]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
  
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

Epoch 1/500
53/53 [==============================] - 1s 3ms/step - loss: 0.0381
Epoch 2/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0132
Epoch 3/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0110
Epoch 4/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0100
Epoch 5/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0094
Epoch 6/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0090
Epoch 7/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0087
Epoch 8/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0082
Epoch 9/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0079
Epoch 10/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0076
Epoch 11/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0073
Epoch 12/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0070
Epoch 13/500
53/53 [=================

In [13]:
model.save('barn.h5')

In [4]:
model = tf.keras.models.load_model('barn.h5')

In [5]:
for i in range(5,10):
  df = pd.read_csv(f"C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn{i}.csv")
  lst = [i for i in range(0,121)]
  X = df.iloc[:, lst].values
  y = df.iloc[:, [123,124,125]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
  
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

Epoch 1/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 2/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0036
Epoch 3/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0033
Epoch 4/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0032
Epoch 5/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 6/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 7/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0030
Epoch 8/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0029
Epoch 9/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0028
Epoch 10/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0028
Epoch 11/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0028
Epoch 12/500
53/53 [==============================] - 0s 2ms/step - loss: 0.0027
Epoch 13/500
53/53 [=================

In [6]:
for i in range(10,15):
  df = pd.read_csv(f"C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn{i}.csv")
  lst = [i for i in range(0,121)]
  X = df.iloc[:, lst].values
  y = df.iloc[:, [123,124,125]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
  
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

Epoch 1/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0062
Epoch 2/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0051
Epoch 3/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0048
Epoch 4/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0046
Epoch 5/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0045
Epoch 6/500
53/53 [==============================] - 0s 4ms/step - loss: 0.0043
Epoch 7/500
53/53 [==============================] - 0s 4ms/step - loss: 0.0043
Epoch 8/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0042
Epoch 9/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0041
Epoch 10/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0041
Epoch 11/500
53/53 [==============================] - 0s 4ms/step - loss: 0.0040
Epoch 12/500
53/53 [==============================] - 0s 3ms/step - loss: 0.0040
Epoch 13/500
53/53 [=================

In [7]:
for i in range(15,20):
  df = pd.read_csv(f"C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn{i}.csv")
  X = df.iloc[:, lst].values
  y = df.iloc[:, [123,124,125]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
  
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

Epoch 1/500
54/54 [==============================] - 0s 4ms/step - loss: 0.0082
Epoch 2/500
54/54 [==============================] - 0s 4ms/step - loss: 0.0068
Epoch 3/500
54/54 [==============================] - 0s 4ms/step - loss: 0.0064
Epoch 4/500
54/54 [==============================] - 0s 4ms/step - loss: 0.0062
Epoch 5/500
54/54 [==============================] - 0s 5ms/step - loss: 0.0060
Epoch 6/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0059
Epoch 7/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0058
Epoch 8/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0057
Epoch 9/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 10/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 11/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 12/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0054
Epoch 13/500
54/54 [=================

In [8]:
for i in range(20,28):
  df = pd.read_csv(f"C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn{i}.csv")
  lst = [i for i in range(0,121)]
  X = df.iloc[:, lst].values
  y = df.iloc[:, [123,124,125]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
    
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

Epoch 1/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0062
Epoch 2/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0052
Epoch 3/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 4/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0048
Epoch 5/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 6/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 7/500
54/54 [==============================] - 0s 3ms/step - loss: 0.0045
Epoch 8/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 9/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 10/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 11/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 12/500
54/54 [==============================] - 0s 2ms/step - loss: 0.0041
Epoch 13/500
54/54 [=================

In [ ]:
for i in range(25,31):
  df = pd.read_csv(f'/content/drive/MyDrive/features/ds{i}.csv')
  lst = [i for i in range(0,121)]
  X = df.iloc[:, lst].values
  y = df.iloc[:, [121,122,123]].values
  X_train = np.asarray(X).astype('float32')
  y_train = np.asarray(y).astype('float32')
  #X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.3)
  
  # train the model using backpropagation
  model.fit(X_train, y_train, epochs=500, batch_size=400)
  # evaluate the model on test data
  loss = model.evaluate(X_train, y_train,verbose=0)
  # print the accuracy
  print('Loss:', loss)

## Loss Evaluation

In [9]:
model.save('barn.h5')

In [22]:
# evaluate the model on test data
loss = model.evaluate(X_test, y_test,verbose=0)

# print the accuracy
print('Loss:', loss)

NameError: name 'X_test' is not defined

# Testing for single Image

In [10]:
#loading the model
model = tf.keras.models.load_model('barn.h5')

In [11]:
#features of test image
df = pd.read_csv("C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn_feature17.csv")
df.head()

Var1_1    Var1_2    Var1_3    Var1_4    Var1_5    Var1_6    Var1_7  \
0  0.768627  0.768627  0.768627  0.768627  0.768627  0.768627  0.768627   
1  0.768627  0.760784  0.749020  0.737255  0.725490  0.713725  0.698039   
2  0.713725  0.698039  0.682353  0.674510  0.674510  0.658824  0.643137   
3  0.631373  0.631373  0.631373  0.631373  0.631373  0.631373  0.631373   
4  0.678431  0.650980  0.631373  0.627451  0.611765  0.584314  0.576471   

     Var1_8    Var1_9   Var1_10  ...  Var1_117  Var1_118  Var1_119  Var1_120  \
0  0.780392  0.776471  0.768627  ... -1.609342 -2.189112 -0.777987  1.451258   
1  0.764706  0.745098  0.721569  ... -0.108528 -0.303997  1.503739 -0.735777   
2  0.713725  0.698039  0.674510  ... -0.228747 -0.157360 -0.632050  1.227000   
3  0.643137  0.635294  0.639216  ... -0.252775 -0.384883  0.233358  0.274870   
4  0.682353  0.658824  0.643137  ...  0.200823 -0.243400 -0.135325 -0.467892   

   Var1_121  Var2  Var3    Var4_1    Var4_2    Var4_3  
0  2.560519     4     3  0.737255  0.772549  0.831373  
1 -4.889871    10     4  0.682353  0.717647  0.784314  
2 -1.802815    15     4  0.603922  0.635294  0.709804  
3  2.618763    21     3  0.603922  0.635294  0.682353  
4 -0.190241    28     4  0.600000  0.627451  0.698039  

[5 rows x 126 columns]

In [12]:
lst = [i for i in range(0,121)]
input= df.iloc[:,lst].values
x= df.iloc[:, 121].values
y= df.iloc[:, 122].values
#input = np.asarray(X).astype('float32')
#y = np.asarray(y).astype('float32')
len(input)

2130

In [40]:
# Import the necessary libraries and load the trained model
import tensorflow as tf
model = tf.keras.models.load_model('barn.h5')

# Define the input data for the model
# Generate the output using the predict method
output = model.predict(input)
# Print the output
print((output))
output=output*255
output=np.ndarray.round(output, decimals=0,out=None)
#output=output.astype(int)
print((output))
len(output)

67/67 [==============================] - 0s 1ms/step
[[0.628443   0.8085556  0.9067809 ]
 [0.7683467  0.71402466 0.6184341 ]
 [0.56655246 0.6604017  0.74137586]
 ...
 [0.39806023 0.4232664  0.3700363 ]
 [0.41256142 0.49325943 0.44525984]
 [0.66582996 0.6716626  0.57139987]]
[[160. 206. 231.]
 [196. 182. 158.]
 [144. 168. 189.]
 ...
 [102. 108.  94.]
 [105. 126. 114.]
 [170. 171. 146.]]


2130

In [25]:
x=x.astype(int)
y=y.astype(int)

In [41]:
from PIL import Image
# Load the RGB image
rgb_img = Image.open("C:\\Users\\shrut\\OneDrive\\Desktop\\miniproject\\code(20.3.23)\\barn\\sun_adbvepquncrfwbft.jpg")
rgb_img=rgb_img.resize((320, 240))

# Convert the image to grayscale
grayscale_img = rgb_img.convert('L')
grayscale_img.save('gray_barn17.png')
# Load the grayscale image
img = Image.open('gray_barn17.png')

for i in range(0,len(output)):
  a=x[i]-1
  b=y[i]-1
# Convert the RGB values to grayscale intensity
  intensity = int(0.2989 * output[i][0] + 0.5870 * output[i][1] + 0.1140 * output[i][2])
    # Replace the pixel value in the grayscale image with the intensity value
  img.putpixel((b,a), intensity)
print("hi")

# Convert the grayscale image back to RGB
rgb_img = img.convert('RGB')
print("hi")
for i in range(0,len(output)):
  a=x[i]-1
  b=y[i]-1
print("hi")
# Set the RGB values of the interest points
rgb_img.putpixel((b,a), tuple(output[i]))
print("hi")
# Save the modified image
rgb_img.save('color_barn17.png')
rgb_img.size
rgb_img

hi
hi
hi


TypeError: 'numpy.float32' object cannot be interpreted as an integer

In [ ]:
image = Image.open("/content/sun_akxkraecdemenrwt.jpg")
image=image.resize((320,240))
# Get the RGB value of each pixel
pixels = image.load()
width, height = image.size
for x in range(width):
    for y in range(height):
        print([x,y])
       # print(f"Pixel ({x}, {y}): R = {r}, G = {g}, B = {b}")

NameError: ignored